name: Price Drop Checker

on:
  schedule:
    - cron: "0 */12 * * *"   
  workflow_dispatch:         

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Start Backend Server
        working-directory: ./Backend
        env:
          PORT: 5000
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}

        run: |
          PORT=5000 nohup node Server.js > server.log 2>&1 &
          sleep 8


      - name: Run price drop check
        run: node Utility/priceDropChecker.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
