name: Run Flight Price Scraper

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Start Backend Server
        working-directory: ./Backend
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: |
          nohup node Server.js > server.log 2>&1 &
          sleep 8

      - name: Run scraper
        working-directory: ./Backend
        env:
          supabaseUrl: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          supabaseServiceRole: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: |
          node Utility/CronScraper.js
